#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Application.Resource", IsApplication=true)]

namespace Application
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int buttonSignStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonUploadPicStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int CameraIconlong = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int demoPic = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_text_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_search = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int listViewClickStyleGreen = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int listViewClickStyleWhite = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int splash = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int transparent = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080013
			public const int btnCheckFile = 2131230739;
			
			// aapt resource value: 0x7f080011
			public const int btnCreatFile = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int btnCreate = 2131230725;
			
			// aapt resource value: 0x7f08001c
			public const int btnEnableDrawing = 2131230748;
			
			// aapt resource value: 0x7f08001e
			public const int btnEnableErasing = 2131230750;
			
			// aapt resource value: 0x7f08001b
			public const int btnImageProcess = 2131230747;
			
			// aapt resource value: 0x7f080020
			public const int btnSave = 2131230752;
			
			// aapt resource value: 0x7f08001d
			public const int btnVSdismiss = 2131230749;
			
			// aapt resource value: 0x7f08000c
			public const int etSearch = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int imageView1 = 2131230735;
			
			// aapt resource value: 0x7f08000b
			public const int listView = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int llContainer = 2131230726;
			
			// aapt resource value: 0x7f080019
			public const int paintView1 = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int paintView2 = 2131230746;
			
			// aapt resource value: 0x7f080021
			public const int search = 2131230753;
			
			// aapt resource value: 0x7f080010
			public const int textView1 = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int textView2 = 2131230734;
			
			// aapt resource value: 0x7f08001f
			public const int textViewdp = 2131230751;
			
			// aapt resource value: 0x7f080002
			public const int txtAge = 2131230722;
			
			// aapt resource value: 0x7f08000d
			public const int txtCreateAccount = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int txtError = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int txtFirstName = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int txtGender = 2131230723;
			
			// aapt resource value: 0x7f080009
			public const int txtHeaderAge = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int txtHeaderFirstName = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int txtHeaderGender = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int txtHeaderLastName = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int txtLastName = 2131230721;
			
			// aapt resource value: 0x7f080012
			public const int txtOr = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int txtUploadPic = 2131230740;
			
			// aapt resource value: 0x7f080017
			public const int txtUploadPicAge = 2131230743;
			
			// aapt resource value: 0x7f080015
			public const int txtUploadPicFirstName = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int txtUploadPicGender = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int txtUploadPicLastName = 2131230742;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialogCreatFile = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FileList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int row_friend = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int upload_picture = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int actionbar = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int CustomActionBarTheme = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int MyActionBar = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
